---
- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - subversion

- name: Create www directories
  file:
    path: '/var/www/{{ item.host }}'
    state: directory
  with_items: '{{ wordpress_sites }}'

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: '/tmp/{{ item.host }}.tar.gz'
  with_items: '{{ wordpress_sites }}'

- name: Create extraction directories
  file:
    path: '/tmp/{{ item.host }}'
    state: directory
  with_items: '{{ wordpress_sites }}'

- name: Extract WordPress
  unarchive:
    src: '/tmp/{{ item.host }}.tar.gz'
    dest: '/tmp/{{ item.host }}'
  with_items: '{{ wordpress_sites }}'

- name: Copy WordPress files
  command: 'cp -R /tmp/{{ item.host }}/wordpress/. /var/www/{{ item.host }}'
  with_items: '{{ wordpress_sites }}'

- name: Copy sample config file
  command: 'mv /var/www/{{ item.host }}/wp-config-sample.php /var/www/{{ item.host }}/wp-config.php'
  args:
    creates: '/var/www/{{ item.host }}/wp-config.php'
  with_items: '{{ wordpress_sites }}'

# This is a tarball of content from the uploads directory that would normally
# get populated after importing content from the Theme Unit Test
# https://codex.wordpress.org/Theme_Unit_Test
# https://raw.githubusercontent.com/WPTRT/theme-unit-test/master/themeunittestdata.wordpress.xml
- name: Download files for uploads directory
  get_url:
    url: https://drive.google.com/uc?id=1rMvj7XhHJr23NqA0tech6RTsqL3g-ptV&export=download
    dest: /tmp/wordpress-uploads.tar.gz

- file:
    path: /tmp/wordpress-uploads
    state: directory

- name: Extract uploads
  unarchive:
    src: /tmp/wordpress-uploads.tar.gz
    dest: /tmp/wordpress-uploads

- name: Copy files into uploads directory
  command: 'cp -R /tmp/wordpress-uploads/uploads/. /var/www/{{ item.host }}/wp-content/uploads'
  with_items: '{{ wordpress_sites }}'

- name: Update ownership of WordPress files
  file:
    path: '/var/www/{{ item.host }}'
    recurse: yes
    state: directory
    owner: '{{ apache_user }}'
    group: '{{ apache_group }}'
  with_items: '{{ wordpress_sites }}'

- name: Update WordPress config database name
  lineinfile:
    dest: '/var/www/{{ item.host }}/wp-config.php'
    regexp: "define\\('DB_NAME', '(.)+'\\);"
    line: "define('DB_NAME', '{{ item.database_name }}');"
  with_items: '{{ wordpress_sites }}'

- name: Update WordPress config database username
  lineinfile:
    dest: '/var/www/{{ item.host }}/wp-config.php'
    regexp: "define\\('DB_USER', '(.)+'\\);"
    line: "define('DB_USER', '{{ item.database_name }}');"
  with_items: '{{ wordpress_sites }}'

- name: Update WordPress config database password
  lineinfile:
    dest: '/var/www/{{ item.host }}/wp-config.php'
    regexp: "define\\('DB_PASSWORD', '(.)+'\\);"
    line: "define('DB_PASSWORD', '{{ wp_db_password }}');"
  with_items: '{{ wordpress_sites }}'
