---
- name: install mysql server
  apt: name={{ item }} state=present
  with_items:
    - python-mysqldb # required for ansible to interact with mysql
    - mysql-server-5.5 # the mysql server
    - mysql-client-core-5.5 # mysql client
    - libmysqlclient-dev # needed for header files for php

- name: create my.cnf for logging in as root
  template:
    src: 'my.cnf.j2'
    dest: '/root/.my.cnf'
    mode: 0600

- name: update mysql root password for root user
  mysql_user:
    name: '{{ mysql_root_username }}'
    password: '{{ mysql_root_password }}'
    check_implicit_admin: yes
    state: present

- name: allow mysql to be accessed from other servers
  lineinfile: dest=/etc/mysql/my.cnf backrefs=yes regexp='^bind-address.*127.0.0.1' line='bind-address = 0.0.0.0'

- name: create databases
  mysql_db:
    name: '{{ item.database_name }}'
    state: present
  with_items: '{{ wordpress_sites }}'
  register: create_databases

- name: setup mysql users for localhost
  mysql_user:
    name: '{{ item.database_name }}'
    password: '{{ wp_db_password }}'
    priv: '{{ item.database_name }}.*:ALL'
    state: present
  with_items: '{{ wordpress_sites }}'
  when: create_databases.changed

- name: restart mysql
  service:
    name: 'mysql'
    state: restarted
